[package]
name = "coal"
description = "General purpose programming language"
version = "0.1.0"
edition = "2021"
authors = ["Andrew X. Shah <drewshah0@gmail.com>"]
repository = "https://github.com/drewxs/coal"
readme = "README.md"
license = "Apache-2.0"
