[package]
name = "coal-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
coal-core = { path = "../coal-core" }
coal-objects = { path = "../coal-objects" }
thiserror = "2.0.12"
